version: '3'

services:

  server:
    container_name: server
    image: nginx:latest
    restart: always
    working_dir: /etc/nginx
    
    volumes:
      - ./src:/src
      - ./data/tmp:/temp
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/server/nginx.conf:/etc/nginx/nginx.conf
      - ./config/server/sites-available:/etc/nginx/sites-available
      - ./config/server/sites-available:/etc/nginx/sites-enabled
      - ./logs/server:/var/log/nginx
  
  php:
    container_name: php
    restart: always
    
    build:
      context: ./config/php
      dockerfile: Dockerfile
    
    volumes:
      - ./src:/src
      - ./data/tmp:/temp
      - ./config/php/php.ini:/usr/local/etc/php/php.ini
      - ./config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
        
  db:
    container_name: db
    image: mysql:latest
    restart: always
    working_dir: /temp
    
    volumes:
      - ./data/db:/var/lib/mysql
      - ./logs/db:/var/log/mysql
      - ./data/tmp:/temp
      
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: admin